name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Fazer checkout dos arquivos
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.EC2_SSH_KEY}}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-3-89-243-205.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Testar conexão SSH
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-3-89-243-205.compute-1.amazonaws.com "echo Conexão SSH bem-sucedida"

    - name: Copiar arquivos com rsync
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ ubuntu@ec2-3-89-243-205.compute-1.amazonaws.com:/home/ubuntu
